name: Practice
version: '${project.version}'
main: dev.revere.alley.AlleyPlugin
authors: ["Emmy", "Remi"]
description: '${project.description}'
website: https://discord.gg/revere
softDepend:
  - PlaceholderAPI
depend: [WorldEdit]