auto-update: true
command:
  anti-syntax-message: '&cYou cannot execute {argument}.'
  syntax-bypass-perm: Practice.owner
  grant-cosmetic-permission-command: permission set {player} {permission}
spawn:
  join-location: world:3.268123135271546:116.0:-8.63107726890665:210.42116:18.046986
game:
  blocked-commands:
  - kill
  - gamemode
  - troll
  lives: 3
  portal-radius: 5
essentials:
  emojis: true
explosive:
  enabled: true
  values:
    range: 3.0
    speed: 1.2
    vertical: 0.8
    horizontal: 1.2
    tnt-fuse-ticks: 80
parkour:
  starter-location: world:-5.1145064347201865:69.0:40.13243289901497:-1.9397448:20.588186
arena:
  default-display-name:
    shared: '&c{arena-name}'
    standalone: '&c{arena-name}'
    ffa: '&c{arena-name}'
kit:
  default-values:
    display-name: '&c{kit-name}'
    description: ''
    disclaimer: '&7{kit-name} kit disclaimer.'
    menu-title: '&c{kit-name}'
blocked-crafting-items: []
profanity-filter:
  add-default-words: false
  staff-notification-format: '&c[S] &f(&cPractice: &cProfanity Detected) &c{player}&f:
    &7{message}'
  filtered-words:
  - shit
  - fuck
  - bitch
